---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a full development environment on ECS
Parameters:
  ShouldCreateNetworkInfrastructure:
    Type: String
    Description: Whether to create the network infrastructure or not
    AllowedValues: ['true', 'false']
    Default: 'true'
  DesiredEnvironmentCount:
    Type: Number
    Description: The number of environments to spin up
    MinValue: 1
    Default: 1

Conditions:
  CreateNetworkResources: !Equals
    - !Ref ShouldCreateNetworkInfrastructure
    - 'true'

Resources:
  DevEnvTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Volumes: []
      NetworkMode: awsvpc
      Memory: 2048
      Cpu: 512
      ExecutionRoleArn: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ecsTaskExecutionRole'
      PlacementConstraints: []
      Family: devenv
      ContainerDefinitions:
        - Name: devenv-instance
          Image: yashdalfthegray/devenv
          Essential: true

  DevEnvCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: 'dev-env-cluster'

  Vpc:
    Condition: CreateNetworkResources
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  PublicSubnet:
    Condition: CreateNetworkResources
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: Vpc
      CidrBlock: 10.0.0.0/24
      AvailabilityZone:
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region

  InternetGateway:
    Condition: CreateNetworkResources
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Condition: CreateNetworkResources
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: Vpc
      InternetGatewayId:
        Ref: InternetGateway

  RouteViaIgw:
    Condition: CreateNetworkResources
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: Vpc

  PublicRouteViaIgw:
    Condition: CreateNetworkResources
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: RouteViaIgw
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  PublicSubnetRouteTableAssociation:
    Condition: CreateNetworkResources
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: RouteViaIgw

  DevEnvSecurityGroup:
    Condition: CreateNetworkResources
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the load test tasks
      VpcId:
        Ref: Vpc

  DevEnvService:
    Condition: CreateNetworkResources
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: DevEnvCluster
      DesiredCount:
        Ref: DesiredEnvironmentCount
      LaunchType: FARGATE
      ServiceName: load-test-service
      TaskDefinition:
        Ref: DevEnvTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Ref: DevEnvSecurityGroup
          Subnets:
            - Ref: PublicSubnet
